image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

install:
  stage: build
  script:
    - npm install

build:
  stage: build
  needs:
      - install
  script:
    - npm run build
  artifacts:
    expire_in: 1 month
    when: on_success
    paths:
        - main.js
        - manifest.json
        - styles.css

release:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: build
      artifacts: true
  rules:
      - if: $CI_COMMIT_TAG # Run this job when a tag is created
  script:
      - echo "running release_job"
  release:
      tag_name: '$CI_COMMIT_TAG'
      description: '$CI_COMMIT_TAG'
  artifacts:
    expire_in: never
    when: on_success
    paths:
        - main.js
        - manifest.json
        - styles.css

